tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "oven-sh/bun"
tap "withgraphite/tap"

brew "bash"
brew "bat"
brew "bun"
brew "chezmoi"
brew "deno"
brew "ffmpeg"
brew "fnm"
brew "fzf"
brew "git"
brew "lsd"
brew "mas"
brew "micro"
brew "pnpm"
brew "rustup"
brew "starship"
brew "tlrc"
brew "tmux"
brew "wget"
brew "withgraphite/tap/graphite"
brew "zellij"
brew "zoxide"
brew "zsh"

cask "1password"
cask "1password-cli"
cask "affinity-designer"
cask "affinity-photo"
cask "affinity-publisher"
cask "aldente"
cask "android-studio"
cask "authy"
cask "balenaetcher"
cask "bartender"
cask "blender"
cask "chatgpt"
cask "cleanmymac"
cask "curseforge"
cask "devutils"
cask "discord"
cask "docker"
cask "firefox"
cask "flutter"
cask "folx"
cask "font-hack-nerd-font"
cask "ghostty"
cask "google-chrome"
cask "iina"
cask "insta360-studio"
cask "istat-menus"
cask "jetbrains-toolbox"
cask "keka"
cask "lunar"
cask "microsoft-excel"
cask "microsoft-powerpoint"
cask "microsoft-word"
cask "minecraft"
cask "netspot"
cask "plex"
cask "postman"
cask "proton-mail"
cask "protonvpn"
cask "raycast"
cask "renamer"
cask "rocket"
cask "slack"
cask "spotify"
cask "steelseries-gg"
cask "steam"
cask "synology-chat"
cask "synology-drive"
cask "synology-surveillance-station-client"
cask "tailscale"
cask "viscosity"
cask "visual-studio-code"
cask "warp"
cask "zoom"

mas "Compressor", id: 424390742
mas "Final Cut Pro", id: 424389933
mas "Home Assistant", id: 1099568401
mas "Logic Pro", id: 634148309
mas "LosslessCut", id: 1505323402
mas "Magnet", id: 441258766
mas "MainStage", id: 634159523
mas "Messenger", id: 1480068668
mas "Motion", id: 434290957
mas "PastePal", id: 1503446680
mas "Screens 5", id: 1663047912
mas "TextSniper", id: 1528890965
mas "WireGuard", id: 1451685025
mas "Xcode", id: 497799835
mas "Yoink", id: 457622435
